name: OrangeFox - Build (Pure Xperia 1V Edition)

on:
  workflow_dispatch:
    inputs:
      MANIFEST_BRANCH:
        description: 'OrangeFox 源码清单分支'
        required: true
        default: '12.1'
        type: choice
        options:
        - 12.1
        - 14.1
      DEVICE_TREE:
        description: 'Xperia 1 V 设备树 GitHub 链接'
        required: true
        default: 'https://github.com/sony-sm8550-TWRP/device_sony_pdx234-TWRP'
      DEVICE_TREE_BRANCH:
        description: '设备树仓库的分支'
        required: true
        default: 'android-12.1'
      DEVICE_PATH:
        description: '设备树在源码中的存放路径'
        required: true
        default: 'device/sony/pdx234'
      DEVICE_NAME:
        description: '设备代号'
        required: true
        default: 'pdx234'
      BUILD_TARGET:
        description: '构建目标 (索尼1V必须选择 vendorboot)'
        required: true
        default: 'vendorboot'
        type: choice
        options:
        - boot
        - recovery
        - vendorboot
      USE_CCACHE:
        description: 使用 ccache 进行加速编译
        type: boolean
        required: true
        default: true

jobs:
  build:
    name: Build OrangeFox by ${{ github.actor }}
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
    - name: Clean-up
      uses: rokibhasansagar/slimhub_actions@main

    - name: Build Environment
      run: |
        sudo apt install aria2 linux-modules-extra-$(uname -r) zram-tools -y
        git clone https://gitlab.com/OrangeFox/misc/scripts.git -b master
        cd scripts
        sudo bash setup/android_build_env.sh
        cd .. && rm -rf scripts
        sudo apt autoclean >/dev/null || true
        sudo apt autoremove -qy 2>/dev/null || true
        sudo rm -rf /var/cache/apt/archives/ 2>/dev/null || true

    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: '3072'

    - name: Checkout
      uses: actions/checkout@main

    - name: Setup ccache
      uses: hendrikmuhs/ccache-action@v1.2
      if: inputs.USE_CCACHE
      with:
        max-size: "2G"
        create-symlink: true

    - name: Setup zram
      run: |
        sudo modprobe zram
        sudo sed -i 's/^#PERCENT=50/PERCENT=90/' /etc/default/zramswap
        sudo sed -i 's/^#PRIORITY=100/PRIORITY=1000/' /etc/default/zramswap
        sudo systemctl restart zramswap
        zramctl

    - name: Set-up Manifest
      if: inputs.MANIFEST_BRANCH == '12.1' || inputs.MANIFEST_BRANCH == '14.1'
      run: |
        mkdir -p ${GITHUB_WORKSPACE}/OrangeFox
        cd ${GITHUB_WORKSPACE}/OrangeFox
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
        git clone https://gitlab.com/OrangeFox/sync.git -b master
        cd sync
        ./orangefox_sync.sh --branch ${{ inputs.MANIFEST_BRANCH }} --path ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}

    - name: Clone Android13+ Dependencies For 12.1 Branch
      if: inputs.MANIFEST_BRANCH == '12.1'
      run: |
        cd ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}
        sed -i 's/<project name="android_hardware_qcom_bootctrl" path="hardware\/qcom-caf\/bootctrl" remote="LineageOS" revision="lineage-19.1-caf" \/>/<project name="android_hardware_qcom_bootctrl" path="hardware\/qcom-caf\/bootctrl" remote="LineageOS" revision="lineage-21.0-caf" \/>/g' ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}/.repo/manifests/twrp-default.xml
        sed -i '/<!-- Include phh'\''s treble repo for lptools support -->/i \    <!-- Include libmicrohttpd for TWRP -->\n    <project name="adontoo/android_external_libmicrohttpd" path="external/libmicrohttpd" remote="github" revision="ofox-14.1" />\n' ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}/.repo/manifests/twrp-default.xml
        sed -i '/<project path="bootable\/recovery" name="android_bootable_recovery" remote="TeamWin" revision="android-12.1"\/>/d' ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}/.repo/manifests/twrp-default.xml
        mv ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}/bootable/recovery ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}/bootable/recovery-ofrp
        repo sync
        mv ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}/bootable/recovery-ofrp ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}/bootable/recovery
        cd ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}/bionic/
        wget "https://github.com/adontoo/OrangeFox-android_platform_bionic/commit/85b1a7100083006927376f30bb8a67885c6dd71f.patch" -O bionic.patch
        git am bionic.patch
        cd ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}/external/libmicrohttpd
        sed -i 's/^static enum MHD_Result send_response/static enum MHD_Result __attribute__((unused)) send_response/' server.c

    - name: Clone Device Tree
      run: |
        cd ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}
        git clone ${{ inputs.DEVICE_TREE }} -b ${{ inputs.DEVICE_TREE_BRANCH }} ./${{ inputs.DEVICE_PATH }}
        cd ${{ inputs.DEVICE_PATH }}
        echo "COMMIT_ID=$(git rev-parse HEAD)" >> $GITHUB_ENV

    - name: Inject OrangeFox Mandatory Macros
      run: |
        CONF="${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}/${{ inputs.DEVICE_PATH }}/BoardConfig.mk"
        echo "" >> $CONF
        echo "# ==========================================" >> $CONF
        echo "# OrangeFox Specs Injected Auto" >> $CONF
        echo "FOX_VERSION := \"R12.1_Xperia1V\"" >> $CONF
        echo "OF_MAINTAINER := \"SelfBuilt\"" >> $CONF
        echo "FOX_AB_DEVICE := 1" >> $CONF
        echo "TARGET_NO_RECOVERY := true" >> $CONF
        echo "ALLOW_MISSING_DEPENDENCIES := true" >> $CONF
        echo "# ==========================================" >> $CONF

    - name: Building OrangeFox
      run: |
        cd ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}
        set +e
        export FOX_BUILD_DEVICE=${{ inputs.DEVICE_NAME }}
        if [[ ${{ inputs.USE_CCACHE }} == true ]]; then
        export USE_CCACHE=1
        export CCACHE_EXEC=/usr/bin/ccache
        sed -i 's/return sandboxConfig\.working/return false/g' build/soong/ui/build/sandbox_linux.go
        fi
        source build/envsetup.sh
        export ALLOW_MISSING_DEPENDENCIES=true
        set -e
        if [[ ${{ inputs.MANIFEST_BRANCH }} == '14.1' ]]; then
        lunch twrp_${{ inputs.DEVICE_NAME }}-ap2a-eng && make clean && mka adbd ${{ inputs.BUILD_TARGET }}image
        else
        lunch twrp_${{ inputs.DEVICE_NAME }}-eng && make clean && mka adbd ${{ inputs.BUILD_TARGET }}image
        fi

    - name: Set Release Properties
      run: |
        echo "BUILD_DATE=$(TZ=Asia/Shanghai date +%Y%m%d)" >> $GITHUB_ENV
        cd ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}
        DEVICE_TREE_URL="${{ inputs.DEVICE_TREE }}"
        if [[ "${DEVICE_TREE_URL}" == *.git ]]; then
          DEVICE_TREE_URL="${DEVICE_TREE_URL%.git}"
        fi
        echo "DEVICE_TREE_URL=${DEVICE_TREE_URL}" >> $GITHUB_ENV

    - name: Upload to Release
      uses: softprops/action-gh-release@master
      with:
        files: |
          OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}/out/target/product/${{ inputs.DEVICE_NAME }}/vendor_boot.img
          OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}/out/target/product/${{ inputs.DEVICE_NAME }}/OrangeFox*.zip
        name: OrangeFox Recovery for ${{ inputs.DEVICE_NAME }} // ${{ env.BUILD_DATE }}
        tag_name: ${{ github.run_id }}
        body: |
          ## OrangeFox Recovery Build for Xperia 1V
          Build Branch: fox_${{ inputs.MANIFEST_BRANCH }}
          Device Tree: [Link](${{ env.DEVICE_TREE_URL }}/tree/${{ inputs.DEVICE_TREE_BRANCH }})
